global_args:
  exist_on_existence: true
  exp_name_suffix: batch_test
list:
  - model_path: /work/nvme/bbvf/mtian8/LLM/data/checkpoint_long_32k_4096
    model_type: llama
    save_base_path: /u/yufengd4/work/models
    rope_theta: 1000000
    training_step: 100
    auto_range: false
    s_len: 100
    e_len: 0
  - model_path: /work/nvme/bbvf/mtian8/LLM/data/checkpoint_long_32k_4096
    model_type: llama
    save_base_path: /u/yufengd4/work/models
    rope_theta: 1000000
    training_step: 200
    auto_range: false
    s_len: 100
    e_len: 100


